### ISSUE TITLE
Missing node dependencies

### ISSUE THREAD

**Issue by RyanParsley** [tylerbeck/generator-power#7]
After a clean install grunt failed due to missing packages:
- imagemin-mozjpeg
- imagemin-zopfli

**Comment by tylerbeck** [comment]
I am unable to reproduce this when selecting all default options... please provide selected options, node and npm version.

**Comment by RyanParsley** [comment]
```
npm -v
1.4.28

node -v
v0.10.35
```

I believe the only option that I changed from default was using sass. 

I presumed this was from you having those two dependancies installed globally, did you confirm that's not the case?
